import localFont from "next/font/local";
import "./globals.css";
import Footer from "./components/layout/front/Footer";
import Header from "./components/layout/front/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
